
@extends('layouts.main')

@section('content')
<section class="section mg-t-80-sm mg-t-140-lg"><div class="container"><div class="row-flex flex-col"><div class="ev-sm-12 ev-md-8 center-block"><h1 class="title-primary_medium text-center mg-b-20">Mitsubishi Virtual Assistant Chat <br> Syarat dan Ketentuan Penggunaan Mitsubishi Virtual Assistant Chat</h1></div><div class="ev-sm-12 ev-md-8 center-block"><h1>DEFINISI</h1><ol class="mg-b-20 text-stretch pd-l-30-sm pd-r-15-sm"><li class="mg-b-10 leading-relax"><b>Mitsubishi Virtual Assistant Chat</b>, atau <b>Mira Chat</b> adalah layanan customer care <i>chatbot</i> milik PT. Mitsubishi Motors Krama Yudha Sales Indonesia (MMKSI)  berbasis aplikasi chatting yang dapat diakses langsung oleh Pengguna melalui <i>smartphone</i> atau gawai <i>(gadget)</i>.</li><li class="mg-b-10 leading-relax">Pengguna dapat mengetahui informasi seputar layanan Mitsubishi Motors serta dapat melakukan percakapan dengan Live Agen secara online untuk menyampaikan pertanyaan, keluhan dan hal lain terkait produk dan layanan Mitsubishi. </li><li class="mg-b-10 leading-relax">Pengguna adalah pihak yang menggunakan <b>Mira Chat</b> pada situs Mitsubishi Indonesia, Aplikasi My Mitsubishi Motors ID dan 
    Aplikasi <i>chatting Whatsapp</i></li><li class="mg-b-10 leading-relax"><i>Live Agen</i> adalah <i>customer service</i> Mitsubishi yang bertugas melayani percakapan langsung dengan Pengguna melalui 
    <b>Mitsubishi Virtual Assistant Chat.</b></li><li class="mg-b-10 leading-relax"><i>Widget</i> <b>Mira Chat</b> adalah jendela percakapan/<i>window</i> chat yang terdapat pada situs dan aplikasi Mitsubishi.</li><li class="mg-b-10 leading-relax"><i>OTP (One Time Password)</i> adalah kode sandi yang bersifat unik yang dihasilkan oleh sistem Mitsubishi dan dikirimkan dalam bentuk email atau sms yang terdaftar pada <b>Mira Chat</b>.</li><li class="mg-b-10 leading-relax">Kegiatan yang dapat dilakukan oleh Pengguna melalui <b>Mira Chat</b> yaitu: Lihat Produk, Service Booking, Emergency Service, Lihat Promo, Lihat Event, Cari Dealer, Layanan Purna Jual, Layanan Test Drive, Simulasi Pembayaran, Konsultasi Pembelian, Notifikasi, FAQ dan Live Agen.</li></ol><h1>PENGGUNAAN MIRA CHAT</h1><ol class="mg-b-20 text-stretch pd-l-30-sm pd-r-15-sm"><li class="mg-b-10 leading-relax">Untuk dapat menggunakan layanan <b>Mira Chat</b>, Pengguna dapat mengakses melalui situs 
    <a href="https://mitsubishi-motors.co.id">mitsubishi-motors.co.id</a>,
    atau Aplikasi My Mitsubishi Motors ID, dan Aplikasi <i>chatting WhatsApp</i> yang perlu di unduh dari toko aplikasi seperti 
    <i>app store</i> atau <i>play store</i>.</li><li class="mg-b-10 leading-relax">Apabila Pengguna menggunakan layanan melalui Aplikasi 
    <i>chatting WhatsApp</i>, pengguna harus mendaftarkan nomor telepon seluler resmi Mitsubishi Motors (official business account) pada aplikasi. Pengguna wajib memastikan nomor telepon yang didaftarkan pada aplikasi chatting adalah nomor telepon seluler resmi Mitsubishi Motors (official business account). Segala akibat yang timbul karena didaftarkannya nomor telepon seluler milik pihak lain menjadi tanggung jawab Pengguna sepenuhnya, dan pengguna dengan ini membebaskan Mitsubishi dari segala macam tuntutan, gugatan, dan/atau tindakan hukum lainnya dari pihak manapun.</li><li class="mg-b-10 leading-relax">Langkah awal menggunakan <b>Mira Chat</b>, Pengguna harus terlebih dahulu memasukkan data yang diperlukan seperti nama, alamat email, dan nomor telepon milik Pengguna.</li><li class="mg-b-10 leading-relax">Untuk dapat menggunakan menu layanan service seperti Service Booking, Test Drive, Emergency Service dan lain lain, pengguna diharuskan memiliki akun My Mitsubishi Motors ID terlebih dahulu, jika pengguna belum memiliki akun, pengguna dapat melakukan registrasi pada <b>Mira Chat</b> di situs web atau aplikasi <i>chatting whatsapp</i>.</li><li class="mg-b-10 leading-relax">Kode OTP akan dikirimkan via email atau sms. Segala akibat yang timbul karena didaftarkannya alamat email atau nomor telepon milik pihak lain menjadi tanggung jawab Pelanggan sepenuhnya dan Pengguna dengan ini membebaskan Mitsubishi Motors dari segala macam tuntutan, gugatan, dan/atau tindakan hukum lainnya dari pihak manapun.</li><li class="mg-b-10 leading-relax">Dengan melakukan registrasi pada <b>Mira Chat</b>, Pengguna dengan ini telah mengetahui, tunduk dan menyetujui, dan tunduk pada Ketentuan Mitsubishi Virtual Assistant Chat dan Ketentuan Privacy Policy. PT Mitsubishi Motors Krama Yudha Sales Indonesia (MMKSI) berhak mengubah ketentuan-ketentuan terkait <b>Mira chat</b> yang akan diberitahukan oleh Mitsubishi Indonesia dalam bentuk dan melalui sarana apa pun sesuai ketentuan hukum yang berlaku.</li></ol><h1>KETENTUAN PENGGUNAAN</h1><ol class="mg-b-20 text-stretch pd-l-30-sm pd-r-15-sm"><li class="mg-b-10 leading-relax">Setelah memasukkan data yang diperlukan, Pengguna dapat memulai sesi percakapan di <i>Widget</i> <b>Mira Chat</b>. Apabila Pengguna mengakses 
    <b>Mira Chat</b> melalui aplikasi <i>chatting Whatsapp</i>, 
    pengguna perlu terlebih dahulu menyapa Mira pada awal percakapan.</li><li class="mg-b-10 leading-relax">Permintaan informasi yang dapat dilayani oleh Live Agen melalui 
    <b>Mira Chat</b> adalah informasi terkait produk dan layanan Mitsubishi.</li><li class="mg-b-10 leading-relax">Untuk menjaga keamanan data Pengguna, Pengguna dilarang untuk menyampaikan informasi yang bersifat rahasia, misalnya 
    <i>Personal Identification Number</i> atau <i>One Time Password</i>, 
    saat sesi percakapan berlangsung.</li><li class="mg-b-10 leading-relax">Bila dalam jangka waktu 10 (menit) atau jangka waktu lain yang ditentukan, tidak ada respon dari Pengguna saat sesi percakapan berlangsung maka 
    <b>Mira Chat</b> berhak mengakhiri sesi percakapan.</li><li class="mg-b-10 leading-relax">Agar Pengguna dapat secara maksimal menikmati layanan yang diberikan via <b>Mira Chat</b>, Pengguna disarankan untuk menggunakan jenis dan versi aplikasi <i>browser</i> yang diinformasikan oleh Mira dari ke waktu ke waktu dalam bentuk dan melalui sarana apa pun sesuai ketentuan yang berlaku.</li></ol></div><div class="ev-sm-12 ev-md-8 center-block"><h1>PENANGANAN KELUHAN (PENGADUAN)</h1><p>Pengaduan mengenai layanan Mira Chat dapat disampaikan oleh Pengguna kepada Mitsubishi Motors Customer Care Service Mitsubishi Indonesia, melalui email: 
        <a href="mailto:mmcc@mitsubishi-motors.co.id">mmcc@mitsubishi-motors.co.id</a> atau telepon <a href="tel:08041300300">0804-1-300-300</a>.</p></div></div></div></section>
@endsection